name: flutter_map_floating_marker_titles
description: Floating Map Marker Titles for flutter_map
version: 0.0.6
repository: https://github.com/chtk3131/flutter_map_floating_marker_titles

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  latlong2: ^0.8.1

  flutter_floating_map_marker_titles_core:
    git:
      url: https://github.com/chtk3131/flutter_map_floating_marker_titles.git
  # Uncomment and use this a dependency when working locally
  #flutter_floating_map_marker_titles_core:
  #  path: ../flutter_floating_map_marker_titles_core
  flutter_map: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
